version: '3.7'

services:
  app:
    container_name: skeleton
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - api
    env_file:
      - .env
    ports:
      - "3000:3000"
    depends_on:
      - db
    restart: always

  db:
    container_name: postgres
    image: postgres
    networks:
      - api
    env_file:
      - .env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    restart: always

networks:
  api:
volumes:
  pgdata:
